// Domain types — single source of truth from shared
export type {
  MoneyLoverTransaction,
  TransactionSource,
  DebtType,
  NewDebt,
  Debt,
  DebtSettlement,
  DebtSettlementInput,
  BudgetStatus,
  NewBudget,
  Budget,
  DashboardAccountTypeKey,
  DashboardPreferences,
  DashboardPreferencesInput,
  NotificationEventPriority,
  NotificationEventStatus,
  NotificationEventDeliveryMode,
  JsonPrimitive,
  JsonValue,
  JsonObject,
  NewNotificationEvent,
  NotificationEvent,
  NewTransaction,
  Transaction,
  Category,
  CategoryGroup,
  CategoryMapping,
  Account,
  NewAccount,
  CreditCardPaymentReminderFields,
  CreditCardPaymentConfirmationInput,
  CreditCardPaymentConfirmationResult,
  ImportBatch,
  TransactionFilter,
  Statistics,
  ImportResult,
  AdjustmentNote,
  TransferNote,
  TransferParams,
} from "@money-insight/shared/types";

export {
  DASHBOARD_ACCOUNT_TYPE_KEYS,
  DASHBOARD_PREFERENCES_ID,
  normalizeDashboardAccountTypeKeys,
} from "@money-insight/shared/types";

// UI-specific types
export type {
  ProcessedTransaction,
  CategorySpending,
  MonthlyAnalysis,
  YearlyAnalysis,
  SpendingBottleneck,
  DateRangeFilter,
  FilterState,
  DailySpending,
  DailyAverageSpending,
  MonthlyReport,
} from "@money-insight/shared/types";
